### ISSUE TITLE
Native C/CPP solution for small embedded systems?

### ISSUE THREAD

**Issue by acidtonic** [bluesky-social/atproto#111]
Is there a native C/CPP solution for small embedded systems? Would love to see something more low level for places that node is far too large to run on.

I envision small MIPS low power data harvesting/gathering devices similar to weather stations being able to connect up and offer services from solar power.

Interesting project :)

**Comment by dholms** [comment]
Yes we'll absolutely be publishing this software in a systems language. If you trawl back through the git history, you'll see that the server originally started out as a go server.

Since this code will run in the browser, we have to support JS & we wanted to avoid implementing data structures in more than one language in the exploratory phase, so we just did everything in TS/node.

As the implementation becomes more stable, we'll start looking to implement everything in a systems language. In all likelihood go or rust

**Comment by whyrusleeping** [comment]
To add on to @dholms 's response, the individual components that make up this protocol are designed to be small and simple, thus (hopefully) making them easy to reimplement.
