### ISSUE TITLE
ENS Domains as Handles

### ISSUE THREAD

**Issue by haideralipunjabi** [bluesky-social/atproto#1204]
**Is your feature request related to a problem? Please describe.**

It's not a major problem, but I feel the owners of ENS Domains (.eth) would like to use them as handles.

**Describe the solution you'd like**

I think the only way to solve this right now is to extend the `/.well-known/atproto-did` method to `.eth` domains as well. [eth.limo](https://eth.limo/) can be used for easier implementation.

**Additional context**

I may have jumped the gun with this one, but I have already made a PR (#1200) for this.  I though creating an issue to discuss this is important.

**Comment by DavidBuchanan314** [comment]
I see plenty of users already using `*.eth.limo` handles, presumably via the `/.well-known/atproto-did` verification method. IMHO, the implementation in your PR only serves to obfuscate the centralized dependency on `eth.limo`, which is still present in either case.

**Comment by dholms** [comment]
We're trying to be very conservative with extensibility of core functionality, because any of that logic must be implemented by _every_ service in the network.

For that reason, we only support two curves (p256 & k256), two did methods (web & plc) & two handle resolution methods (DNS & well-known).

That's not to say we won't allow additional methods at some point. However right now we do not want to take on a dependency on a blockchain network.

Thanks for the excitement and effort!
