### ISSUE TITLE
/xrpc endpoint should be under /.well-known

### ISSUE THREAD

**Issue by agentjabsco** [bluesky-social/atproto#1211]
as previously mentioned [here][1] and [here][2] and [here][3]/[here][4]/[here][5]

[1]: https://bsky.app/profile/blahaj.life/post/3juukqehncd2v
[2]: https://bsky.app/profile/dholms.xyz/post/3juugrs6sus2j
[3]: https://bsky.app/profile/cia.fyi/post/3juuh3vxa3c2h
[4]: https://bsky.app/profile/cia.fyi/post/3juva6neha52s
[5]: https://bsky.app/profile/cia.fyi/post/3jycgw6jvaw2w

**Comment by Cloudhunter** [comment]
All those linked posts are about the DID resolving, which is already at .well-known https://github.com/bluesky-social/atproto/commit/743eaf1cf0757b0a34507ae64065b1365d354a98

I'm not sure what this would achieve otherwise, and .well-known is not used as somewhere to put an API anywhere else on the web to my knowledge.

**Comment by bnewbold** [comment]
The HTTP handle resolution endpoint specifically has been moved out of XRPC entirely and is a separate API under `/.well-known`. The (newish) spec for this is here: https://atproto.com/specs/handle#https-well-known-method

It wouldn't be wild to discuss moving all the other XRPC endpoints under `/.well-known/` as well, but that would be a long conversation and it isn't clear if that is what is being proposed here.

I'm going to close this issue now. If you want to discuss moving other API endpoints under `/.well-known/`, that is probably best as a github discussion topic (under this same repo), instead of filing an issue.
