### ISSUE TITLE
Since we're talking slurs, can we stop vulgar usernames?

### ISSUE THREAD

**Issue by ruralTom** [bluesky-social/atproto#1349]
**Is your feature request related to a problem? Please describe.**

A lot of vulgar, offensive and inappropriate terms are in usernames beyond just slurs.

**Describe the solution you'd like**

Add cunt, cum, slut, whore, cock, jizz (for a start) to the block list. 

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by DenowRammy** [comment]
Vulgarities and curses are just as valid a form of self-expression as any other. I disagree with this suggestion as I don't think it's in anyone's benefit to have these words blocked off from handles, except potentially future advertisers should the eventually turn that way.

Even for those who do not wish to see such vulgar terms, having these handles available creates, for you, a shorthand for people whose content you will likely find distasteful or offensive. In such case, could you not personally use handles as a pre-screen similar to the warnings on impersonation and spam built into the protocol?

I don't see what material benefit this suggestion would have for users, their content, or their ability to self-express.

An alternative to this may be to add muted words, and have the ability to include user handles and usernames in what's muted, so that individuals such as yourself who do not wish to see content that includes such terms will not have to. A robust curation tool that allows you to mute others on such a basis would give you power over seeing such terms, or any others you may find disagreeable that the public zeitgeist generally doesn't ("ass", "damn", "dumb", etc).

**Comment by DavidBuchanan314** [comment]
@DenowRammy and others: I don't think @ruralTom has opened this issue in good faith, engage with caution.

**Comment by ruralTom** [comment]
I don't know why you'd say this. Usernames with derogatory slang terms bring down the quality of bluesky. No one needs vulgarity of that level in their user name to communicate.

Jul 17, 2023 1:42:31 PM David Buchanan ***@***.***>:

**Comment by ruralTom** [comment]
I was thinking far more vulgar than profanity, but you make good points.

Jul 17, 2023 3:57:56 AM DenowRammy ***@***.***>:

**Comment by dholms** [comment]
We will support vulgarity filters at some point so that if you don't want to see vulgarity it can be filtered out of your view. However we won't be preventing creation of any non-slur vulgarity
