### ISSUE TITLE
Behavior of `app.bsky.feed.searchPosts`

### ISSUE THREAD

**Issue by myConsciousness** [bluesky-social/atproto#1856]
Hi!

This may be the currently intended behavior, but there were a few things that I want to check about using `app.bsky.feed.searchPosts`.

## The structure of the returned object differs from Lexicon

The output of `app.bsky.feed.searchPosts` is saying it returns `posts`, `hitsTotal` and `cursor` as follows, but only `posts` is actually returned.

```json
      "output": {
        "encoding": "application/json",
        "schema": {
          "type": "object",
          "required": ["posts"],
          "properties": {
            "cursor": { "type": "string" },
            "hitsTotal": {
              "type": "integer",
              "description": "count of search hits. optional, may be rounded/truncated, and may not be possible to paginate through all hits"
            },
            "posts": {
              "type": "array",
              "items": {
                "type": "ref",
                "ref": "app.bsky.feed.defs#postView"
              }
            }
          }
        }
      },
```

## `limit=1` will return an empty `posts`?

This returns an empty `posts`.

```bash
GET https://bsky.social/xrpc/app.bsky.feed.searchPosts?q=test&limit=1
```

```json
{"posts":[]}
```

But if I set `limit=2` in the same query, I get only one `posts` item.

```bash
GET https://bsky.social/xrpc/app.bsky.feed.searchPosts?q=test&limit=2
```

```json
{"posts":[{"$type":"app.bsky.feed.defs#postView","record":{"$type":"app.bsky.feed.post","text":"test","createdAt":"2098-12-31T15:00:00.000Z"},"author":{"did":"did:plc:wpyvghtrmnflwxmknbz67vct","handle":"shinyakato.bsky.social","viewer":{"muted":false,"blockedBy":false,"followedBy":"at://did:plc:wpyvghtrmnflwxmknbz67vct/app.bsky.graph.follow/3k7nhbxedcq27"},"labels":[{"src":"did:plc:wpyvghtrmnflwxmknbz67vct","uri":"at://did:plc:wpyvghtrmnflwxmknbz67vct/app.bsky.actor.profile/self","cid":"bafyreiaqoa4663mnvtgltphngag2pjao6m7wme6mi326j4yraroqt2o4ry","val":"alt-account","neg":false,"cts":"1970-01-01T00:00:00.000Z"}]},"uri":"at://did:plc:wpyvghtrmnflwxmknbz67vct/app.bsky.feed.post/3k5mfs5jt4c22","cid":"bafyreihqegfrtcnc4v4xoztqyrkyyxd5zdipfp6ktzr2ps4lgfcipmrbfm","replyCount":0,"repostCount":0,"likeCount":0,"viewer":{},"labels":[],"indexedAt":"2023-08-23T08:31:30.597Z"}]}
```

Perhaps the `limit` passed in the parameter is not interpreted correctly.

**Comment by bnewbold** [comment]
@dholms I think the `presentation` layer is missing the `cursor` and `hitsTotal` here:
https://github.com/bluesky-social/atproto/pull/1845/files#diff-1b2449ec0fc17027c31f4bea261ec5ea70083c5cf84987deec76e8c3c2caea48R105

in terms of the response length not being the same, I think what is happening is that for the specific query you are doing (`q=test`), the first hit is being removed from the search results, due to a takedown or block relationship. try with another search query.

we might need to document that behavior better: currently such hits are simply removed. we might fetch more results from the backend in the future to make this less likely, but it will always happen in some situations. these removals will probably won't impact `hitsTotal`, for now? I think it is good that we have prioritized not removing results that shouldn't be there though.
