### ISSUE TITLE
Labels `!hide` and `!warn` are taking effect even if labeler doesn't advertise them

### ISSUE THREAD

**Issue by imax9000** [bluesky-social/atproto#2367]
**Describe the bug**

These two labels are still do something and hide content when they're coming from a labeler that doesn't advertise them.

**To Reproduce**

1. Create a labeler. Do not add `!hide` or `!warn` to `labels` or `policies`.
2. Subscribe to labeler with a user account.
3. Apply label `!hide` to some other post or account
4. Open that post or account from the user account from step 2
5. Observe that post/account is hidden

**Expected behavior**

Label should have no effect. User did not consent to sourcing that label from this particular labeler, and has no way to configure the behaviour.

**Additional context**

Non-configurable labels that hide content are bad enough of an intrusion already. What's worse is that there's no indication at subscription time that a particular labeler can issue them and silently remove content from your feed.

**Comment by bnewbold** [comment]
@pfrazee should these labels take effect when they haven't been declared in the `labels` array? I can't remember if we specified/clarified behavior for the non-redact bang labels.

**Comment by imax9000** [comment]
Even if they should - users must be able to configure their behaviour, at least on non-mandatory labelers.

**Comment by mary-ext** [comment]
Here was when I asked whether to interpret label definitions that aren't listed in `labelValues`, it should apply for this case as well
https://bsky.app/profile/did:plc:ragtjsm2j2vknwkz3zp4oxrd/post/3knwb2ufflk2r

**Comment by imax9000** [comment]
Reminder: this is still an issue and a deal-breaker (at least for me) for subscribing to 3rd-party labelers.

**Comment by nekorug** [comment]
I understand users not wanting a moderation service to be able to hide things without any configuration setting, but informational labels can easily clutter the configuration UI. If there was some way to specify that a label that never hides or blurs content wasn't as important and have it appear in a collapsed or hidden state in the UI, that would be nice. Because there is nothing for the user to configure, with the exception of ignoring the label, this shouldn't be an issue. I hope this is a good compromise.

**Comment by mary-ext** [comment]
Right now it affects local labeler-defined labels as well, and it's not clear whether they are:
1. Not ready to be used by clients (is being tested by advertising them publicly)
2. Intended to be non-configurable
3. Intended to be hidden
4. Misconfiguration on the labeler's part

**Comment by bnewbold** [comment]
Now that we've had a bit of time for the labeling system to bake, what i'm leaning towards:

- for "regular" mod services (labelers), only the declared values in `labelValues` can take effect, and no "bang" (`!`-prefixed) labels should be applied by the client, even if included in `labelValues`
- "global" or "common" labels can be used as self-labels. The governance of this set is sort of up in the air, but for now it is just what the bsky app allows. These labels can be included in `labelValues` without an entry in `labelValueDefinitions`, but all other labels (eg, labels specific to a mod service) need to be in both `labelValues` *and* `labelValueDefinitions` or they get ignored. I think it is permissible to *also* include a `labelValueDefinitions` for a global/common label, which would override the global definition/semantics (eg, allow a mod service to provide their own definition of what the label means), but this is a corner-case and I wouldn't recommend doing this for now.
- the "bang" labels can be used by mod services with the "redact" flag set in local client config. these are basically "full-power" and usually mandatory labelers. the current example is the Bluesky Moderation Service in the Bluesky Social app. the pattern we expect is that apps will define a small number of "full-power" labelers (could be more than one), and that these are more tightly bound to app clients (mobile apps, desktop apps, etc) than they are to appviews. the "bang" labels are "global", and do not need to be included in `labelValues` or `labelValueDefinitions`; and actually can not be configured / overridden per-labeler. we also call the bang labels "imperative" labels: they specify a behavior, but not a reason. this can be a helpful escape hatch when there isn't a more specific label yet, or the semantics of a situation are unclear, but are less accountable or policy-driven, and are probably not appropriate for most mod services.
- we likely need some kind of notification or warning in-app when a mod service changes their `labelValues` or `labelValueDefinitions` sets. This is important so users know if additional content is now being "hidden" from their view of the network.

**Comment by imax9000** [comment]
Spotted in the wild: https://bsky.app/profile/did:plc:36h6ttx2g23zqr4accilbvo7/post/3kw5dhxv2572e

![image](https://github.com/bluesky-social/atproto/assets/654649/68a8dab6-c109-41ef-aa98-59382d237c4e)

**Comment by imax9000** [comment]
This has remained unfixed for too long. It's now a de facto part of labeler capabilities and should not be taken away lightly.

**Comment by widrs** [comment]
that is a very poor approach to take.

bluesky preens and prides about its open protocols, but the data model backing labelers is one of the least open and most ridiculously opaque systems that could have been created. it's not clear to me that there were many choices available that could have created a _less_ transparent system than the one we have now. labelers' labels are:

* non-enumerable (except indirectly through great effort)
* not directly requestable
* never committed to in whole, and therefore not provable to be not applied
* never provably revoked even in part, either
* presented in a data model riddled with muddy ambiguity around data validity that leaves ample room for dual interpretations
* only served by the label service themselves, and not functionally mirrorable by any other entity; they are therefore free to deny or serve differing views of what labels they claim to apply depending on who seems to be asking

labelers are a 20% MVP that escaped into the wild and somehow took on life as **THE ONLY** answer to user-for-user moderation service with more nuance than blocklists and mutelists, and they are universally more powerful than the latter and very few users are aware of the fact. the space is ripe for exploitation by bad actors, as if blocklists people signed up for on purpose weren't bad enough.

asking bluesky to require a labeler to declare that they are able to effect the application of global labels or not via their frontend is an absolute bare minimum. the rest of the bullet points up above are not something i can imagine them ever "fixing" -- i do not have that much faith, at this point -- but i want to drive home some of my personal understanding of what would make it such a terrible idea to just let them run with this ability with zero changes *just because they've had it so far.*
