### ISSUE TITLE
Already a decentralized federated protocol

### ISSUE THREAD

**Issue by dmbr0** [bluesky-social/atproto#255]
Activitypub already exists. Why not just work on that? Why is this needed?

**Comment by dholms** [comment]
different approach with different tradeoffs

**Comment by pfrazee** [comment]
There are a lot of differing design decisions.

Account portability is a major reason why we chose to build a separate protocol. Signed data repositories and DIDs are both unique to ATP and not terribly easy to retrofit into ActivityPub.

There are smaller things as well: a different viewpoint about how schemas should be handled, a preference for domain usernames over AP’s double-@ email usernames, and the goal of having large scale search and discovery (rather than the hashtag style of discovery that AP favors).

Meta:

The AP community has always been somewhat suspicious of Bluesky, for reasons that are understandable. AP’s community is volunteer driven and the users joined to escape Twitter. So, here we come, a startup funded by Twitter, with strong opinions on how the tech should be done. I’ve heard concerns that we’d “embrace, extend, & extinguish.” I’ve heard concerns that we’d force through changes that people don’t want by dint of being a funded company. You can criticize us for going a different direction but I think it’d have been a difficult collaboration if we chose to use AP, especially since we weren’t willing to compromise on some of the decisions above.

**Comment by chingon81** [comment]
> Activitypub already exists. Why not just work on that? Why is this needed?

I did not authorize anyone to tamper with my information why as people keep stealing my shit you bunch of road motherfuckers yeah pissing me off and I keep stealing my data packing my shit you fucking wrote motherfuckers pay me motherfucker Knigge do

**Comment by dmbr0** [comment]
No suspicion from me, just genuinely curious what the difference was and why not go that direction. I appreciate the answer.

**Comment by dmbr0** [comment]
> > Activitypub already exists. Why not just work on that? Why is this needed?
> 
> I did not authorize anyone to tamper with my information why as people keep stealing my shit you bunch of road motherfuckers yeah pissing me off and I keep stealing my data packing my shit you fucking wrote motherfuckers pay me motherfucker Knigge do

I can't even make sense of this. What are you trying to say?
