### ISSUE TITLE
`chat.bsky.convo.getLog` on api.bsky.chat returning no logs for account with chat messages

### ISSUE THREAD

**Issue by snarfed** [bluesky-social/atproto#2760]
Hi! I'm trying to use `chat.bsky.convo.getLog` on api.bsky.chat to poll for chat logs for an account on an external PDS. The account has chat messages, but `getLog` consistently returns `logs: []`. I'm successfully making other calls to api.bsky.chat for this account, eg `getConvoForMembers` and `sendMessage`.

I'm sure I'm doing something wrong, I just haven't managed to figure out what yet.  The account is `did:plc:xbifsywyv5pka5jlknhv5yv3`, on PDS `https://atproto.brid.gy`. I've included an example response below. Let me know if I can answer any questions. Feel free to move this to any other repo if appropriate. cc @bnewbold, re https://github.com/snarfed/bridgy-fed/issues/966. Thanks in advance!

```json
{
  "cursor": "22222222zxmwf",
  "logs": []
}
```

**Comment by devinivy** [comment]
This endpoint has a slightly funny semantic, which is that it starts "now" rather than from the beginning of time.  The intended use case is to use it to apply changes on top of some current state that you already have.  So a typical flow might look like:
 - start polling `convo.getLog` and buffering any logs that may come back.
 - fetch a conversation you want to view with `convo.getConvo`.
 - apply buffered logs to the `convo.getConvo` response.
 - continue polling `convo.getLog` and applying incoming changes.

In these cases you can tell whether a change from the log needs to be applied by comparing the `rev` found in a the log to the `rev` of the corresponding convo or message—only newer `rev`s need be applied.

Using this strategy the Bluesky app, for example, never fetches user logs going back to the beginning of time.  If you need to you should be able to do this, though, by passing the "zero-cursor" `2222222222222`.

**Comment by snarfed** [comment]
Ahhh thank you! OK, funny semantic indeed, but I get it now. So after the first time, I should pretty much always pass a cursor.

...and it looks like logs are returned starting from that cursor, in ascending order, so I could probably ignore `rev` altogether? ...although I expect cursor ordering is best effort, and `rev` is authoritative, so I should still use `rev` to be safe.

Regardless, thanks for the explanation!
