### ISSUE TITLE
Double-check that we're on spec with alsoKnownAs usage

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#329]
The `alsoKnownAs` field is supposed to be an array. Need to make sure we're using it that way and baking in behaviors around multiple values.

**Comment by dholms** [comment]
PLC server returns an array for the document - always with one member 😉 

Our did resolution library just defaults to considering the first object in the array as the username

**Comment by dholms** [comment]
The idea I went with on DID resolution is: 
We can parse the info we need from a PLC DID just fine because we know exactly how it will be shaped (the PLC datamodel guarantees that). If you want to use a different method (web), it's on you to structure it perfectly or else we won't understand it - for instance, ATP handle should be first in alsoKnownAs array. 

We can be more liberal in what we accept later, but this just kept complexity down for now

**Comment by pfrazee** [comment]
Yeah this got brought up in the context of people having multiple handles. If order is significant then we can treat the first one as the primary one. Otherwise we're going to need to think about how we indicate the "main" handle, or just live with amibuity

**Comment by dholms** [comment]
Standard is: "first alsoKnownAs that starts with `at://`"
