### ISSUE TITLE
Include image aspect ratio in embed views

### ISSUE THREAD

**Issue by dholms** [bluesky-social/atproto#427]

**Comment by redsolver** [comment]
I would love for the aspect ratio to be included in embed views:
- Makes it possible to show images with their native aspect ratios in feeds without the layout jumping when loading images
- Makes it possible to render a gallery view of images (similar to Google Photos) for image-only feeds

It would also be nice to have something like https://evanw.github.io/thumbhash/ for images to show during loading or when blurring out images (without needing to load them).

**Comment by aliceisjustplaying** [comment]
ohmygod yes please please thank you.

**Comment by JAManfredi** [comment]
Aspect ratio will work, but what about just adding height and width to be even more granular? Similar to the Twitter API (https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/media)

**Comment by redsolver** [comment]
Is it ok if I create a PR to add optional width and height `integer` fields to the embed lexicon? That would already make it possible for third-party clients to include that data in a standardized way.

**Comment by bnewbold** [comment]
This issue is quite old (Dec 2022), and i'm going to close it.

We spent a lot of time in Winter 2023 discussing how and whether to include image metadata like height, width, or aspect ratio in embed records, or even in the `blob` built-in type. I can't remember all the reasoning why we didn't, but I think it probably had to do with safely and accurately extracting this metadata. There are a lot of security issues parsing binary file formats and I don't think we wanted to do that in-process; it is also possible for malicious clients/PDS/etc to create incorrect metadata.

Don't want to prevent further conversation; please feel free to create a new issue or discussion about this!

**Comment by bnewbold** [comment]
Cross-reference to related issue: https://github.com/bluesky-social/atproto/issues/565

**Comment by redsolver** [comment]
@bnewbold you are already parsing all image files for thumbnail generation / image resizing for the cdn, could you maybe add the width/height data to the CDN image URLs?

**Comment by DavidBuchanan314** [comment]
IMHO this is all trivially solvable if you let the client figure out the dimensions, and embed them in the post record (specifically, an optional field of `app.bsky.embed.images.image`).

The client can "lie" (or be wrong), but the impact of that would be limited to subtle UI jank for anyone viewing their posts (no more than the current levels of pop-in UI jank!)
