### ISSUE TITLE
Add APIs and flows for account deletion

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#474]
- Add 3 new methods
  - Request account deletion
  - Undo account deletion
  - Request account deletion "undo code" email
- Add new email sends
  - One that informs the user that their account is soft deleted
  - One that informs the account has been hard deleted
  - One with an "undo code"
- Update the login route
  - Give a "Account marked for deletion" error if appropriate (this needs to be distinct from "account actually deleted")

Here is the flow:

- User calls "request account deletion" method. Account is soft deleted, notice email is sent, and a timer is started for 1 week to do hard delete.
- After 1 week, the account is hard deleted and the user is emailed.
- If the user tries to log in while soft deleted, an error is thrown.
  - The app will offer to undo the soft delete. If the user hits undo, app will request a the "undo code" from the server. User enters the undo code and sends an "undo deletion" request, which restores the account. (This all mirrors password resets.)

Note: the reason for the 7 day delay and undo code is to avoid the abuse vector of someone nabbing your phone and deleting your account.

**Comment by dholms** [comment]
I was thinking about this a bit this morning, & just wanted to check it against a few thoughts:

If the primary concern here is "slowing down destructive operations", what do we do in the event of an account migration? This is an equivalently or _more_ destructive operation than account deletion, but I have to imagine that we handle it immediately because we can't just put the user's account on pause for 7 days while we wait to migrate.

_Note: to illustrate the destructive behavior, consider migrating to a null host or a host owned by the attacker. This deletes the account & data on the PDS _and_ rotates their PLC keys (altho they still have the 3 day recovery window)_

Also, a user always has the capability of deleting _records_ with no cool down period. Meaning that with a valid auth token they can either manually delete all the contents of a repo, or run a simple script to do so. Altho the cool down period for full account deletion does add some extra friction here.

This is adding a new "state" that an account can be in & we have to think about how this gets exposed to the network. On "soft delete", are subscribers notified that the account was "hard deleted"? Or do we introduce the concept of a "soft delete" into the sync protocol? I lean toward the former. 

I also think that a 7 day cool down period goes a bit against the story of the PDS: "You're my agent in the network. I want you to delete my account, so you should just delete it"

---

This makes me wonder if the check on account deletion should not be "7 day cool down period" but rather "password entry required, with 2fa through email". Automatic local backups (or remote backups) also help with the story here.

Now an attacker must:
- know the password
- have access to email
- delete app on phone

This would let us keep the flow consistent with account migration: "account deletion == account migration to null host"

**Comment by pfrazee** [comment]
Yeah that all makes sense to me. Basically remove the 7 day wait but add an "enter password and reset code" to the action.

**Comment by pfrazee** [comment]
Something we should track in the near future: do DID documents on PLC ever get "deleted" ?

**Comment by dholms** [comment]
I thought about that as well 🤔 

My current thought is that they don't "get deleted", but they could be tombstoned.

Reason for this being that deletion hurts auditability. I think you'd want to publish some signed tombstone so that PLC can prove it did not delete a DID against the accounts will. However the signature on that tombstone is based on the current signing key which is based on the op log for the DID. Which means that a "delete" just needs to be another op on the log.
