### ISSUE TITLE
detectFacets() doesn't add the `did`

### ISSUE THREAD

**Issue by PatrickHeneise** [bluesky-social/atproto#834]
https://github.com/zentered/bluesky-post-action/blob/main/src/post.js#L20

Although I'm passing the agent configuration, `facets[0].features[0].did` is undefined and throws an error in the post validation.

**Comment by thinkverse** [comment]
Ok, I could reproduce the issue, it's caused by `detectFacets` setting the `did` to be an empty string if it cannot resolve the `did` from the handle. Which I'd consider a bug @pfrazee?

https://github.com/bluesky-social/atproto/blob/c70cb2b6e5a350233d451c3d9a5f6cd5f2c003a4/packages/api/src/rich-text/rich-text.ts#L340-L346

For now, you can use some quick filtering to filter out any potential facets that have features with not set values. Here's a quick and dirty version. 👍

```js
// Automatically detect facets.
await rt.detectFacets(agent);

// Filter out any facets with features 
// that have no value set value.
let facets = null

if (rt.facets) {
  facets = rt.facets
    .filter(facet => {
      const features = facet.features
        .filter(feature =>
          feature?.uri && feature?.uri !== '' ||
          feature?.did && feature?.did !== ''
        );

      return features.length > 0;
    });
}

const postRecord = {
  $type: 'app.bsky.feed.post',
  text: rt.text,
  ...facets && { facets },
  createdAt: new Date().toISOString()
}
```

Might not be the cleanest but it does pass the validation if no facets where detected, and if there where some found it'll filter out those with no values on their features. And if it happens that you have a single facets with no feature value it'll attach `facets` with an empty array which again passes validation and posts just fine. 👍

**Comment by PatrickHeneise** [comment]
Thanks! Updated the action with the suggested workaround.

**Comment by chandrn7** [comment]
Still seeing this behavior with `detectFacets`. 

```
{'text': 'gobo test @chandrn.bsky.social', 
'createdAt': '2023-12-10T18:13:09.981+00:00', 
'facets': [{'$type': 'app.bsky.richtext.facet', 'index': {'byteStart': 10, 'byteEnd': 30}, 'features': [{'$type': 'app.bsky.richtext.facet#mention', 'did': ''}]}]}
```
