### ISSUE TITLE
Sync: repo CAR archives have a lot of blocks

### ISSUE THREAD

**Issue by interfect** [bluesky-social/atproto#996]
I'm trying to sync with Bluesky, and I'm getting back CAR archives that seem weirdly huge.

For example, say I want to look at a post on the profile of the account `did:plc:mf5dzzqkp7fnmby6blfeljwj`, which right now seems to have 3664 total records in its Merkle Search Tree. Specifically, say I want to look at `at://did:plc:mf5dzzqkp7fnmby6blfeljwj/app.bsky.feed.post/3jufymasfaw23`.

[My attempt at a client](https://github.com/interfect/skyfall) looks at the URI, pulls out the DID, and naïvely syncs down the whole repo for the account to local storage, the way a Secure Scuttlebutt client might. So I hit `com.atproto.sync.getRepo` and I get a whole CAR file in the response. It's about 12 megabytes, which seems maybe a little big, but not unreasonable.

But when I parse the CAR, I get 33544 blocks. Then I fish out the Merkle Search Tree and find the aforementioned 3664 records.

Why are there so many blocks compared to records? By my read of the protocol, there should be:

* N block to store the N records themselves
* <N blocks to store <N internal nodes, because the tree fans out exponentially.
* One block for the signed commit at the head
* Some blocks for old versions of the tree, since the current commit points to previous commits. If N records are added in N commits, this would be N for the commits, and then like N log N for the paths to the root in the tree.

Somehow this is adding up to like 10 * N blocks for N commits.

My best guess is that log base 2 of 3664 is about 11, and so after a while each record adds a block for itself, a block for the commit to add it, and like 10 new blocks going up the tree to the new root.

Is this supposed to happen? Is there a reason that each record maybe gets its own commit and all the old ones stay in the repo? Can I get a CAR of just the current commit?

(Can I get off the waitlist so I don't have to write a client?)

**Comment by ianklatzco** [comment]
contact me for an invite ^^

**Comment by devinivy** [comment]
That all pretty much sounds right to me 👍 I think you're looking for the checkout of the repo rather than the full repo.  The full repo is useful for syncing history of the repo while preserving incremental changes, but if you just want the current state of the repository you can ask for a checkout at `com.atproto.sync.getCheckout`.

If we take a look at the block count in the full repo versus the checkout this is what we'll see:
```
❯ curl -s https://bsky.social/xrpc/com.atproto.sync.getCheckout\?did\=did:plc:mf5dzzqkp7fnmby6blfeljwj | npx ipfs-car blocks | wc -l
    5676

❯ curl -s https://bsky.social/xrpc/com.atproto.sync.getRepo\?did\=did:plc:mf5dzzqkp7fnmby6blfeljwj | npx ipfs-car blocks | wc -l  
   34463
```

There are significantly fewer blocks in the checkout than the full repo for the reasons you outlined, in particular each record addition/removal/update will generate new blocks in its path up to the root.  The fanout of the MST is 4, so if there are 3664 leaves in the tree you might expect a depth of around log(3664) / log(4) =~ 6.  A perfect 4-ary tree of depth 6 would have (4^7 - 1) / (4 - 1) = 5461 nodes, so I think we're in the ballpark of the checkout size we'd expect 👍 I don't have the back of the envelope math on the total repo size at hand to say for sure if the 34463 sounds right, but @dholms might.  Anecdotally it doesn't sound _too_ wild to me for a repo of that size.

**Comment by interfect** [comment]
OK, I've tried swapping my `getRepo` call for a `getCheckout` call and I'm now seeing sizes that make more sense for just the current state of the account. I'm worried I'm introducing a race between getting the HEAD and getting the checkout itself, but closing that might be able to wait until I write a real sync that has some notion of what it has synced already to inform what it requests.

I'm going to close this, I think; the resolution is that yes the repo is huge, but the current checkout isn't going to be so huge and generally one is going to want to use that, through the endpoint provided for this purpose.

Thanks for your help!
